CI/CD Setup [Issue#4](https://github.com/Moringa-Learning/attendance_moringa/issues/4)
Moringa-Learning/attendance_moringa pull request #6
Opened 2024-07-22 08:07 UTC by otsembo

Setup CI/CD
Description

2024-07-23 18:25 UTC, otsembo commented
@layersony This PR is ready for review

2024-07-24 02:09 UTC, layersony requested changes

2024-07-24 02:09 UTC, layersony commented on .github/workflows/flask_ci.yaml
> +          export SECRET_KEY="your_secret_key"
Could set Environment variables, I have set them up

DATABASE_URL as `SQLALCHEMY_DATABASE_URI` 
SECRET_KEY as `SECRET_KEY`,

2024-07-24 02:09 UTC, layersony commented on .github/workflows/flask_ci.yaml
> +        env:
Could set Environment variables, I have set them up
POSTGRES_DB as POSTGRES_DB
POSTGRES_USER as POSTGRES_USER
POSTGRES_PASSWORD as POSTGRES_PASSWORD

2024-07-25 18:17 UTC, otsembo commented
@layersony Added credentials to CI

2024-07-25 21:19 UTC, merged